# The 100 Episodes

Library dan/atau module yang digunakan dalam latihan kali ini ialah:

- request (seperti httr pada R)
- BeautifulSoup (seperti rvest pada R)
- pandas (seperti tibble pada R)

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
res = requests.get("https://en.wikipedia.org/wiki/List_of_The_100_episodes")

In [3]:
page = BeautifulSoup(res.text, "html.parser")

In [4]:
episode_tables = page.find_all("table", class_ = "wikitable plainrowheaders wikiepisodetable")

In [5]:
episodes = []
for table in episode_tables:
    headers = []
    for header in table.find("tr").find_all("th"):
        headers.append(header.text)
    for row in table.find_all("tr", class_ = "vevent"):
        values = []
        value = row.find_all("td")
        for col in row.find_all(["th", "td"]):
            values.append(col.text)
        episodes_dict = { headers[i] : values[i] for i in range(len(values))}
        episodes.append(episodes_dict)

In [6]:
df = pd.DataFrame(episodes)
df

,No.overall,No. inseason,Title,Directed by,Written by,Original air date,Prod.code,U.S. viewers(millions),Original air date [96]
0,1,1,"""Pilot""",Bharat Nalluri,Jason Rothenberg,"March 19, 2014 (2014-03-19)",296843,2.73[12],NaN
1,2,2,"""Earth Skills""",Dean White,Jason Rothenberg,"March 26, 2014 (2014-03-26)",2J7052,2.27[13],NaN
2,3,3,"""Earth Kills""",Dean White,Elizabeth Craft & Sarah Fain,"April 2, 2014 (2014-04-02)",2J7053,1.90[14],NaN
3,4,4,"""Murphy's Law""",P. J. Pesce,T. J. Brady & Rasheed Newson,"April 9, 2014 (2014-04-09)",2J7054,1.69[15],NaN
4,5,5,"""Twilight's Last Gleaming""",Milan Cheylov,Bruce Miller,"April 16, 2014 (2014-04-16)",2J7055,1.80[16],NaN
...,...,...,...,...,...,...,...,...,...
95,96,12,"""The Stranger""",Amanda Row,Blythe Ann Johnson,NaN,T27.14062,0.54[108],"August 19, 2020 (2020-08-19)"
96,97,13,"""Blood Giant""",Michael Cliett,Ross Knight,NaN,T27.14061,0.59[109],"September 9, 2020 (2020-09-09)"
97,98,14,"""A Sort of Homecoming""",Jessica Harmon,Sean Crouch,NaN,T27.14065,0.63[110],"September 16, 2020 (2020-09-16)"
98,99,15,"""The Dying of the Light""",Ian Samoil,Kim Shumway,NaN,T27.14064,0.52[111],"September 23, 2020 (2020-09-23)"
99,100,16,"""The Last War""",Jason Rothenberg,Jason Rothenberg,NaN,T27.14066,0.61[112],"September 30, 2020 (2020-09-30)"

In [7]:
# save to csv
df.to_csv("./the-100-episodes.csv", index = False)